---
title: Fox Force Five
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Fox Force Five ASD
email: fff@fff.com
description: |
  FFF is the best!
  Via del Ciap 23
  Somewhere over the Rainbow
  Null Island
show_excerpts: false
minima:
  date_format: "%d/%m/%Y"
  social_links:
    twitter: fff
    rss: rss
    instagram: fff
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
header_pages:
- index.md
- events.markdown
- notizie.markdown
- about.md
