---
title: Fox Force Five
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: FFF
email: fff@fff.com
description: 'FFF is the best!

'
show_excerpts: false
minima:
  date_format: "%Y-%m-%d %H:%M"
  social_links:
    twitter: fff
    rss: rss
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
header_pages:
- index.md
- events.markdown
- about.md
